import logging
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from typing import Dict, Any

from ..config import settings

logger = logging.getLogger("finance_coach.email")


def send_financial_summary_email(email_to: str, report_content: Dict[str, Any]):
    """
    Formulates and sends a weekly health report email to the user.
    Falls back to console logger if SMTP configuration variables are missing.
    """
    stats = report_content.get("statistics", {})
    summary = report_content.get("summary", "")
    tips = report_content.get("actionable_tips", [])
    warnings = report_content.get("habit_warnings", [])
    
    start_date = stats.get("start_date", "")
    end_date = stats.get("end_date", "")
    savings_rate = stats.get("savings_rate", 0.0)
    total_spent = stats.get("total_spending", 0.0)
    
    # HTML Email body
    tips_html = "".join([f"<li>{tip}</li>" for tip in tips])
    warnings_html = "".join([f"<li>{warn}</li>" for warn in warnings]) if warnings else "<li>No negative habits flagged. Keep it up!</li>"
    
    subject = f"Your Weekly Financial Health Report ({start_date} - {end_date})"
    
    html_body = f"""
    <html>
        <body style="font-family: Arial, sans-serif; color: #333333; line-height: 1.6; max-width: 600px; margin: 0 auto; padding: 20px; border: 1px solid #eeeeee; border-radius: 8px;">
            <h2 style="color: #4f46e5; border-bottom: 2px solid #f3f4f6; padding-bottom: 10px;">AI Financial Coach Summary</h2>
            <p>Here is your weekly financial digest for the period <strong>{start_date}</strong> to <strong>{end_date}</strong>.</p>
            
            <div style="background-color: #f9fafb; padding: 15px; border-radius: 6px; margin: 20px 0;">
                <h3 style="margin-top: 0; color: #111827;">Quick Stats</h3>
                <table style="width: 100%; border-collapse: collapse;">
                    <tr>
                        <td style="padding: 5px 0;"><strong>Total Outflow:</strong></td>
                        <td style="text-align: right; color: #ef4444; font-weight: bold;">${total_spent:.2f}</td>
                    </tr>
                    <tr>
                        <td style="padding: 5px 0;"><strong>Savings Rate:</strong></td>
                        <td style="text-align: right; color: #10b981; font-weight: bold;">{savings_rate:.1f}%</td>
                    </tr>
                </table>
            </div>
            
            <h3>Coach Analysis</h3>
            <p style="font-style: italic; background-color: #f5f3ff; border-left: 4px solid #8b5cf6; padding: 10px 15px; border-radius: 4px;">
                "{summary}"
            </p>
            
            <h3>Actionable Tips for Next Week</h3>
            <ul style="padding-left: 20px;">
                {tips_html}
            </ul>
            
            <h3>Habit Warnings</h3>
            <ul style="padding-left: 20px; color: #b91c1c;">
                {warnings_html}
            </ul>
            
            <p style="margin-top: 30px; font-size: 0.85em; color: #6b7280; border-top: 1px solid #eeeeee; padding-top: 15px;">
                This email was auto-generated by your AI Personal Finance Coach app. To configure your settings or update connected accounts, login to your dashboard.
            </p>
        </body>
    </html>
    """
    
    # 1. Fallback to console print if settings are missing
    if not settings.SMTP_HOST or not settings.SMTP_USER or not settings.SMTP_PASSWORD:
        logger.info(f"==== MOCK EMAIL SENT TO {email_to} ====")
        logger.info(f"Subject: {subject}")
        logger.info(f"Summary Text: {summary}")
        logger.info(f"Tips: {tips}")
        logger.info(f"Warnings: {warnings}")
        logger.info(f"========================================")
        return
        
    # 2. Try sending real email via SMTP
    try:
        msg = MIMEMultipart("alternative")
        msg["Subject"] = subject
        msg["From"] = settings.SMTP_FROM_EMAIL
        msg["To"] = email_to
        
        msg.attach(MIMEText(summary, "plain"))
        msg.attach(MIMEText(html_body, "html"))
        
        with smtplib.SMTP(settings.SMTP_HOST, settings.SMTP_PORT) as server:
            server.starttls()
            server.login(settings.SMTP_USER, settings.SMTP_PASSWORD)
            server.sendmail(settings.SMTP_FROM_EMAIL, email_to, msg.as_string())
            
        logger.info(f"Successfully sent financial report email to {email_to}")
        
    except Exception as e:
        logger.error(f"Failed to send email to {email_to} via SMTP: {e}", exc_info=True)
